module.exports = {
  tt8367814: {
    imdbID: "tt8367814",
    Title: "The Gentlemen",
    Released: "2020-01-24",
    Runtime: 113,
    Genres: ["Action", "Crime", "Comedy"],
    Directors: ["Guy Ritchie"],
    Writers: ["Guy Ritchie", "Ivan Atkinson", "Marn Davies"],
    Actors: ["Matthew McConaughey", "Charlie Hunnam", "Michelle Dockery"],
    Plot: "An American expat tries to sell off his highly profitable marijuana empire in London, triggering plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.",
    Poster: "https://m.media-amazon.com/images/M/MV5BMjE2ZjQ4ZGMtZjFhMi00NmI5LTliNjEtODczMWMxNjliZjgxXkEyXkFqcGc@._V1_SX1200.jpg",
    Metascore: 51,
    imdbRating: 7.8
  },

  tt0258463: {
    imdbID: "tt0258463",
    Title: "The Bourne Identity",
    Released: "2002-06-14",
    Runtime: 119,
    Genres: ["Action", "Mystery", "Thriller"],
    Directors: ["Doug Liman"],
    Writers: ["Tony Gilroy", "W. Blake Herron", "Robert Ludlum"],
    Actors: ["Matt Damon", "Franka Potente", "Chris Cooper"],
    Plot: "A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.",
    Poster: "https://m.media-amazon.com/images/M/MV5BYTk1ZTcyMWMtMWUxYS00MmEzLTlmODYtOTk1MGRjOTg1ZjlmXkEyXkFqcGc@._V1_SX1200.jpg",
    Metascore: 68,
    imdbRating: 7.9
  },

  tt0816692: {
    imdbID: "tt0816692",
    Title: "Interstellar",
    Released: "2014-11-07",
    Runtime: 169,
    Genres: ["Adventure", "Drama", "Sci-Fi"],
    Directors: ["Christopher Nolan"],
    Writers: ["Jonathan Nolan", "Christopher Nolan"],
    Actors: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    Plot: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    Poster: "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_SX1200.jpg",
    Metascore: 74,
    imdbRating: 8.7
  },

  tt0240772: {
    imdbID: "tt0240772",
    Title: "Ocean's Eleven",
    Released: "2001-12-07",
    Runtime: 116,
    Genres: ["Crime", "Thriller"],
    Directors: ["Steven Soderbergh"],
    Writers: ["George Clayton Johnson", "Jack Golden Russell", "Harry Brown", "Charles Lederer", "Ted Griffin"],
    Actors: ["George Clooney", "Brad Pitt", "Julia Roberts"],
    Plot: "Danny Ocean rounds up a gang of associates to stage a sophisticated and elaborate casino heist involving three Las Vegas casinos during a popular boxing event.",
    Poster: "https://m.media-amazon.com/images/M/MV5BMmNhZDkxYTgtMDM3ZC00NTQ3LWFjZTUtNzc1Y2QyNWZjNDRmXkEyXkFqcGc@._V1_SX1200.jpg",
    Metascore: 74,
    imdbRating: 7.7
  },

  tt2911666: {
    imdbID: "tt2911666",
    Title: "John Wick",
    Released: "2014-10-24",
    Runtime: 101,
    Genres: ["Action", "Crime", "Thriller"],
    Directors: ["Chad Stahelski"],
    Writers: ["Derek Kolstad"],
    Actors: ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen"],
    Plot: "An ex-hitman comes out of retirement to track down the gangsters who killed his dog and stole his car.",
    Poster: "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_SX1200.jpg",
    Metascore: 68,
    imdbRating: 7.4
  },

  tt1074638: {
    imdbID: "tt1074638",
    Title: "Skyfall",
    Released: "2012-11-09",
    Runtime: 143,
    Genres: ["Action", "Adventure", "Thriller"],
    Directors: ["Sam Mendes"],
    Writers: ["Neal Purvis", "Robert Wade", "John Logan"],
    Actors: ["Daniel Craig", "Javier Bardem", "Naomie Harris"],
    Plot: "James Bond's loyalty to M is tested when her past comes back to haunt her, while MI6 comes under attack.",
    Poster: "https://m.media-amazon.com/images/M/MV5BNjAzMWNkODUtM2FlMi00NzgyLWJhMGUtMWEyNDYyZGFiN2RlXkEyXkFqcGc@._V1_SX1200.jpg",
    Metascore: 81,
    imdbRating: 7.8
  },

  tt0325980: {
    imdbID: "tt0325980",
    Title: "Pirates of the Caribbean: The Curse of the Black Pearl",
    Released: "2003-07-09",
    Runtime: 143,
    Genres: ["Action", "Adventure", "Fantasy"],
    Directors: ["Gore Verbinski"],
    Writers: ["Ted Elliott", "Terry Rossio", "Stuart Beattie"],
    Actors: ["Johnny Depp", "Geoffrey Rush", "Orlando Bloom"],
    Plot: "Blacksmith Will Turner teams up with eccentric pirate Jack Sparrow to save Elizabeth Swann from cursed pirates.",
    Poster: "https://m.media-amazon.com/images/M/MV5BNDhlMzEyNzItMTA5Mi00YWRhLThlNTktYTQyMTA0MDIyNDEyXkEyXkFqcGc@._V1_SX1200.jpg",
    Metascore: 63,
    imdbRating: 8.1
  },

  tt2084970: {
    imdbID: "tt2084970",
    Title: "The Imitation Game",
    Released: "2014-12-25",
    Runtime: 114,
    Genres: ["Biography", "Drama", "Thriller"],
    Directors: ["Morten Tyldum"],
    Writers: ["Graham Moore", "Andrew Hodges"],
    Actors: ["Benedict Cumberbatch", "Keira Knightley", "Matthew Goode"],
    Plot: "During World War II, mathematician Alan Turing tries to crack the German Enigma code with help from fellow code-breakers.",
    Poster: "https://m.media-amazon.com/images/M/MV5BNjI3NjY1Mjg3MV5BMl5BanBnXkFtZTgwMzk5MDQ3MjE@._V1_SX1200.jpg",
    Metascore: 73,
    imdbRating: 8.0
  },

  tt0232500: {
    imdbID: "tt0232500",
    Title: "The Fast and the Furious",
    Released: "2001-06-22",
    Runtime: 106,
    Genres: ["Action", "Crime", "Thriller"],
    Directors: ["Rob Cohen"],
    Writers: ["Ken Li", "Gary Scott Thompson", "Erik Bergquist"],
    Actors: ["Vin Diesel", "Paul Walker", "Michelle Rodriguez"],
    Plot: "An undercover cop infiltrates the world of illegal street racing while investigating a group of suspected hijackers.",
    Poster: "https://m.media-amazon.com/images/M/MV5BZGRiMDE1NTMtMThmZS00YjE4LWI1ODQtNjRkZGZlOTg2MGE1XkEyXkFqcGc@._V1_SX1200.jpg",
    Metascore: 58,
    imdbRating: 6.8
  },

  tt1464335: {
    imdbID: "tt1464335",
    Title: "Uncharted",
    Released: "2022-02-18",
    Runtime: 116,
    Genres: ["Action", "Adventure"],
    Directors: ["Ruben Fleischer"],
    Writers: ["Rafe Judkins", "Art Marcum", "Matt Holloway"],
    Actors: ["Tom Holland", "Mark Wahlberg", "Antonio Banderas"],
    Plot: "Street-smart Nathan Drake is recruited by treasure hunter Victor Sullivan to recover a lost fortune.",
    Poster: "https://m.media-amazon.com/images/M/MV5BYjQxYWNiNzgtOTc2Yi00OGEwLTk5MjAtODdiZTk0ZDJlZGY4XkEyXkFqcGc@._V1_SX1200.jpg",
    Metascore: 45,
    imdbRating: 6.3
  },

  tt0120737: {
    imdbID: "tt0120737",
    Title: "The Lord of the Rings: The Fellowship of the Ring",
    Released: "2001-12-19",
    Runtime: 178,
    Genres: ["Action", "Adventure", "Drama"],
    Directors: ["Peter Jackson"],
    Writers: ["J.R.R. Tolkien", "Fran Walsh", "Philippa Boyens"],
    Actors: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
    Plot: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    Poster: "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX1200.jpg",
    Metascore: 92,
    imdbRating: 8.8,
  },

  tt0085959: {
    imdbID: "tt0085959",
    Title: "The Meaning of Life",
    Released: "1983-03-31",
    Runtime: 107,
    Genres: ["Comedy", "Musical"],
    Directors: ["Terry Jones", "Terry Gilliam"],
    Writers: ["Graham Chapman", "John Cleese", "Terry Gilliam"],
    Actors: ["John Cleese", "Terry Gilliam", "Eric Idle"],
    Plot: "The comedy team takes a look at life in all of its stages in their own uniquely silly way.",
    Poster: "https://m.media-amazon.com/images/M/MV5BZWJkNGY5MDAtYmVkMy00NzdiLTk5MzctMzA0MjMxMDY2NGYwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX1200.jpg",
    Metascore: 72,
    imdbRating: 7.5,
  },

  tt0107048: {
    imdbID: "tt0107048",
    Title: "Groundhog Day",
    Released: "1993-02-12",
    Runtime: 101,
    Genres: ["Comedy", "Drama", "Fantasy"],
    Directors: ["Harold Ramis"],
    Writers: ["Danny Rubin", "Harold Ramis"],
    Actors: ["Bill Murray", "Andie MacDowell", "Chris Elliott"],
    Plot: "A narcissistic, self-centered weatherman finds himself in a time loop on Groundhog Day, and the day keeps repeating until he gets it right.",
    Poster: "https://m.media-amazon.com/images/M/MV5BZWIxNzM5YzQtY2FmMS00Yjc3LWI1ZjUtNGVjMjMzZTIxZTIxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX1200.jpg",
    Metascore: 72,
    imdbRating: 8.1,
  },

  tt0124315: {
    imdbID: "tt0124315",
    Title: "The Cider House Rules",
    Released: "2000-01-07",
    Runtime: 126,
    Genres: ["Drama", "Romance"],
    Directors: ["Lasse Hallström"],
    Writers: ["John Irving"],
    Actors: ["Tobey Maguire", "Charlize Theron", "Michael Caine"],
    Plot: "A compassionate young man, raised in an orphanage and trained to be a doctor there, decides to leave to see the world.",
    Poster: "https://m.media-amazon.com/images/M/MV5BNmY5YzA4OTQtOTQzZS00NDZmLTlhNzQtNzk5NTIyZWE2ZjVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX1200.jpg",
    Metascore: 75,
    imdbRating: 7.4,
  },

  tt0248808: {
    imdbID: "tt0248808",
    Title: "For the Birds",
    Released: "2001-11-02",
    Runtime: 3,
    Genres: ["Animation", "Short", "Comedy"],
    Directors: ["Ralph Eggleston"],
    Writers: ["Ralph Eggleston"],
    Actors: ["Ralph Eggleston"],
    Plot: "A group of snooty birds roosting on a telephone wire get their just deserts when a goofy bird drops in.",
    Poster: "https://m.media-amazon.com/images/M/MV5BZjBhYzgyY2YtMTBhZS00NWIwLWIyYTgtMzhhYmFhZDNkMTQxXkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_SX1200.jpg",
    Metascore: 0.1,
    imdbRating: 8.0,
  }
};
